FROM rocker/shiny

ENV BASEPATH = /home/shiny/
WORKDIR $BASEPATH

COPY init.R .
RUN /usr/local/bin/R --no-init-file --no-save --quiet --slave -f init.R

ENV PORT=8080

COPY server.R run.R ui.R ./
COPY www/* ./www/

# To run on Openshift
COPY ./openshift/uid_entrypoint /
RUN chmod g=u /etc/passwd \
    && chgrp -R 0 $BASEPATH \
    && chmod -R g=u $BASEPATH

ENTRYPOINT [ "/uid_entrypoint" ]

CMD ["/usr/local/bin/R", "--no-save", "--gui-none", "-f run.R"]
