FROM rocker/shiny

WORKDIR /home/shiny/

COPY init.R .
RUN /usr/local/bin/R --no-init-file --no-save --quiet --slave -f init.R

ENV PORT=8080

COPY server.R run.R ui.R ./
COPY www/* ./www/

# To run on Openshift
COPY ./openshift/uid_entrypoint /
RUN chmod g=u /etc/passwd \
    && chgrp -R 0 /app \
    && chmod -R g=u /app

ENTRYPOINT [ "/uid_entrypoint" ]

CMD ["/usr/local/bin/R", "--no-save", "--gui-none", "-f run.R"]
