apiVersion: v1
kind: Service
metadata:
  labels:
    app: covid-monitor
  name: covid-monitor
spec:
  ports:
    - name: tcp-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: covid-monitor
    deploymentconfig: covid-monitor
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
